#!/usr/bin/env Rscript

# Author: Dat T Nguyen <n.dat@outlook.com>
# Date: 15 March 2021
# revised: 15 June 2021

# 06 April 2022
# add model interaction

# This script is use to fit model for imputation R2.

###############
options(stringsAsFactors = FALSE)

if (!require("data.table", quietly = TRUE)) install.packages("data.table")

args = commandArgs(trailingOnly=TRUE)
syntax='\nUsage:\t./imputation_model.R model_Rdata=path/to/model.Rdata df=path/to/af.txt ld=path/to/your/file.ld ld_cutoff=0.8 out_ld=path/to/fitted_ld.txt\n
Input parameters are:
\tmodel_Rdata=path/to/model.Rdata : path to computed model (generated by ./buid_imputation_model.R)
\taf=path/to/af.txt (generated by: bcftoools in previous step.)
\tld=path/to/your/file.ld (generated by Plink 1.9)
\tout_ld=path/to/your/fitted_ld.txt (output is ld file with predicted imputation scores)
\tmodel=interaction or model=linear (model setting is [interaction] that consider interaction term of LD and MAF_taggedSNP In our experiment, interaction model provides slightly better performance than simple linear model. However, we still prefer the simpler model as the performance difference is not significant)\n
\tld_cutoff=0.8 (pairwise R2 cutoff default is 0.8)\n'

model_path = ld_path = af_path = ld_cutoff = out_put_ld_path = model_setting = NA

if(length(args) == 0 ){
  cat("\nNo argument, Program stop! \n")
  cat(syntax)
  quit()
}

for (i in 1:length(args)){
  res=unlist(strsplit(args[i],"="))
  if (res[1] == "model_Rdata") model_path = res[2]
  if (res[1] == "af") af_path = res[2]
  if (res[1] == "ld") ld_path = res[2]
  if (res[1] == "ld_cutoff") ld_cutoff = as.numeric(res[2])
  if (res[1] == "out_ld") out_put_ld_path = res[2]
  if (res[1] == "model") model_setting = res[2]
}

# setwd("/media/datn/data/DatProjects/vn_array/test_full_pipeline")
# imputation_path="test_chr18.Rdata"
# find_snp_path="chr18_find_snp_output.txt"
# ld_path="18_ld_0.2.ld"
# ld_cutoff=0.8


if(is.na(model_path)){
  cat(syntax)
  cat("model_path is not found! Program stop!\n\n")
  quit()
}

if(is.na(ld_path)){
  cat(syntax)
  cat("ld_path is not found! Program stop!\n\n")
  quit()
}

if(is.na(af_path)){
  cat(syntax)
  cat("af_path is not found! Program stop!\n\n")
  quit()
}

if(is.na(out_put_ld_path)){
  out_Rdata_path="ld_fitted_model.txt"
  cat("ld_path is not found! default value is used: \"ld_fitted_model.txt\" \n\n")
}

if ( is.na(model_setting)){
  cat("model setting accepts [model=linear] or [model=interaction] only \n\n")
  cat("Error! Program stop!\n\n")
  quit()
}else if( model_setting != "linear" & model_setting != "interaction"){
  cat("model setting accepts [model=linear] or [model=interaction] only \n\n")
  cat("Error! Program stop!\n\n")
  quit()
}



if ( is.na(ld_cutoff)){
  ld_cutoff = 0.8
  cat("ld_cutoff is not found! default value is used: 0.8 \n\n")
}

load(model_path)
af = fread(af_path, header = TRUE)
af = as.data.frame(af)

ld = fread(ld_path, header = TRUE)
ld = as.data.frame(ld)

pick_col_all = names(ld)
ld$distance = abs(ld$BP_A - ld$BP_B)
ld$R2 = ld$R ^ 2

pick_col = c("BP_A", "BP_B", "R2", "distance")
test_a = test_b = ld[,pick_col]

test_a$tag_AF = af$AF[match(test_a$BP_A, af$POS)]
test_a$tagged_AF = af$AF[match(test_a$BP_B, af$POS)]

test_b$tag_AF = af$AF[match(test_b$BP_B, af$POS)]
test_b$tagged_AF = af$AF[match(test_b$BP_A, af$POS)]

# test_a$R2_2 = test_a$R2^2
# test_a$R2_3 = test_a$R2^3
# test_a$R2_4 = test_a$R2^4

# test_a$tag_AF_2 = test_a$tag_AF^2
# test_a$tag_AF_3 = test_a$tag_AF^3
# test_a$tag_AF_4 = test_a$tag_AF^4

# test_a$tagged_AF_2 = test_a$tagged_AF^2
# test_a$tagged_AF_3 = test_a$tagged_AF^3
# test_a$tagged_AF_4 = test_a$tagged_AF^4

# test_a$distance_2 = test_a$distance^2
# test_a$distance_3 = test_a$distance^3
# test_a$distance_4 = test_a$distance^4

# ##############

# test_b$R2_2 = test_b$R2^2
# test_b$R2_3 = test_b$R2^3
# test_b$R2_4 = test_b$R2^4

# test_b$tag_AF_2 = test_b$tag_AF^2
# test_b$tag_AF_3 = test_b$tag_AF^3
# test_b$tag_AF_4 = test_b$tag_AF^4

# test_b$tagged_AF_2 = test_b$tagged_AF^2
# test_b$tagged_AF_3 = test_b$tagged_AF^3
# test_b$tagged_AF_4 = test_b$tagged_AF^4

# test_b$distance_2 = test_b$distance^2
# test_b$distance_3 = test_b$distance^3
# test_b$distance_4 = test_b$distance^4


if(model_setting == "linear"){
  a = predict(model, test_a)
  b = predict(model, test_b)
}else if(model_setting == "interaction"){
  a = predict(model_interaction, test_a)
  b = predict(model_interaction, test_b)
}else{
  cat("model setting accepts [model=linear] or [model=interaction] only \n\n")
  cat("Error! Program stop!\n\n")
  quit()
}


ld = ld[, pick_col_all]
ld$BP_A_score = a
ld$BP_B_score = b

ld = ld[ld$R^2 >= ld_cutoff,]

fwrite(ld, file = out_put_ld_path, quote = F, sep = "\t", row.names = F)

cat(paste0("\nOutput: ", out_put_ld_path, ".\n"))
cat("Done!\n\n")

